name       : haskell-store-core
version    : 0.4.1
release    : 3
source     :
    - https://hackage.haskell.org/package/store-core-0.4.1/store-core-0.4.1.tar.gz : 145285f9f26a64e9611e01749a0d569691a70fa898f5359bedcfca9dacb064b4
license    : MIT
component  : programming.haskell
summary    : Fast and lightweight binary serialization
description: |
    Fast and lightweight binary serialization
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-primitive
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
