name       : haskell-store-core
version    : 0.3
release    : 1
source     :
    - http://hackage.haskell.org/package/store-core-0.3/store-core-0.3.tar.gz : 8793230b634a310a91db98727dfa6f34a0b7f5ded55985342066d33d98507087
license    : MIT
component  : programming.haskell
summary    : Fast and lightweight binary serialization
description: |
    Fast and lightweight binary serialization
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-primitive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
