name       : haskell-store-core
version    : 0.4.4.2
release    : 5
source     :
    - https://hackage.haskell.org/package/store-core-0.4.4.2/store-core-0.4.4.2.tar.gz : c94185c3c3832ab8195ae17b0535fa020067c0a3f4d550a713eccf03211f8ea0
license    : MIT
component  : programming.haskell
summary    : Fast and lightweight binary serialization
description: |
    Fast and lightweight binary serialization
builddeps  :
    - haskell-cabal-install
    - haskell-primitive-devel
rundeps    :
    - devel:
        - haskell-primitive-devel
networking : yes
setup      : |
    # disable fail
    sed -i "42d" store-core.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
